### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/fewpjs-fewp-example#6]
I completed the previous JS module and am now going back through the new material. This example (with the pillars) is a big picture view that I was completely missing before.
Thank you so much for your dedication to creating and updating the curriculum.
(Maybe this is the wrong place to send this, but I send a lot of "problems" via Issues, and wanted to send something nice for a change.)

**Comment by sgharms** [comment]
Much appreciated. I'll pass this on to my staff.
